### ISSUE TITLE
#include : Failed to compile the shader

### ISSUE THREAD

**Issue by zeroinformatique** [dfranx/SHADERed#139]
I'm trying to add a simple include to my shader:

```
#version 330
#extension GL_GOOGLE_include_directive : require
#include "common.glsl"

in vec4 color;
out vec4 outColor;

void main() {
   outColor = vec4(color);
}
```

ShaderEd finds the included file and compiles it.
I know this because it displays syntax errors correctly if I add some.
But then, the Shader pass fails compilation with the error "Failed to compile the shader(s)"
I tried enabling the logs, but they gave no additional information about what's wrong.

I'm on Windows 10 x64

Any idea?

**Comment by dfranx** [comment]
Thank you for reporting this issue. I've pushed a commit that fixes this. The fix will be available in SHADERed v1.4.2

**Comment by gregschlom** [comment]
For what it's worth, I'm on SHADEREd v1.5.6 and still seeing this exact same issue
